/*! OpticQuiz Colorblind Corrector — content script.
 *
 * Applies a live daltonization correction to whatever page the visitor is on. The popup is the
 * UI; this script just reads the saved mode and paints. No network, no tracking.
 *
 * v1.3 replaced the whole-page SVG filter with the shared engine in widget/engine.js. The
 * filter was applied to document.documentElement, which meant it recolored photographs, made
 * the root a containing block for position:fixed and sticky descendants on other people's
 * sites, and — because the transform moves lightness as well as hue — could push text below
 * WCAG AA. Measured on opticquiz.com's own twelve text/background pairs, it pushed eight below
 * AA, worst 3.22:1 on a pair that passes at 4.80:1 uncorrected. An accessibility extension
 * must not do that to the web.
 *
 * Now text is forced to pure black or white against its corrected backdrop (>= 4.58:1 by
 * construction), graphics take the full matrix, and raster content is never touched.
 * Generated from widget/engine.js — do not edit this file; edit the engine and rebuild. */
  if (window.__oqCx) return;
  window.__oqCx = true;

  var KEY = "oq-cx-mode";
  var SKEY = "oq-cx-strength";          // 0-100; scales the GRAPHIC correction only
  var PKEY = "oq-cx-profile";
  var current = null, strength = 100;

  // The extension runs on sites we have never seen, so it is more conservative than the site
  // widget about how much DOM it is willing to walk before standing down.
  var engine = OQ_ENGINE.create(window, {
    styleId: "oq-cx-sheet", attr: "data-oq-cx", uiAttr: "data-oq-cx-ui", maxElements: 7000
  });

  var repaintTimer = null;
  function apply(mode, pct) {
    if (typeof pct === "number") strength = pct;
    current = (mode && OQ_ENGINE.M[mode]) ? mode : null;
    engine.paint(current, strength);
  }
  function repaintSoon() {
    clearTimeout(repaintTimer);
    repaintTimer = setTimeout(function () { if (current) engine.paint(current, strength); }, 140);
  }

  // Restore the saved mode as early as possible.
  try {
    chrome.storage.local.get([KEY, SKEY], function (r) {
      apply(r && r[KEY], r && typeof r[SKEY] === "number" ? r[SKEY] : 100);
    });
  } catch (e) {}

  // ---- measured severity, from the person's own test ------------------------------
  // On opticquiz.com ONLY, read the on-device results the vision tests store and set the
  // correction strength from them. A content script shares its page's origin storage, so
  // this needs no extra permission and touches no other site.
  //
  // This closes the loop the literature says is missing: severity-personalized correction
  // normally requires a clinical diagnosis, which is why Hue4U (2025) had to build an
  // FM-100 test into a headset. The test is already here and free.
  function syncProfile() {
    if (location.hostname !== "opticquiz.com" && location.hostname !== "www.opticquiz.com") return;
    var raw;
    try { raw = localStorage.getItem("oq-results-v1"); } catch (e) { return; }
    if (!raw) return;
    var d;
    try { d = JSON.parse(raw); } catch (e) { return; }
    var t = d && d.tests; if (!t) return;

    // Same precedence the site uses: the arrangement test grades finer than a five-plate
    // screen. Kept in sync with assets/oq-results.js deliberately.
    var prof = null;
    if (t.d15 && t.d15.data && typeof t.d15.data.totalError === "number" &&
        t.d15.data.dominantAxis && t.d15.data.dominantAxis !== "none") {
      prof = { type: t.d15.data.dominantAxis,
               severity: Math.max(0, Math.min(1, (t.d15.data.totalError - 12) / 60)) };
    } else if (t.color && t.color.data && t.color.data.ctrlOK !== false &&
               typeof t.color.data.rgCorrect === "number") {
      var c = t.color.data, rg = c.rgTotal ? (c.rgTotal - c.rgCorrect) / c.rgTotal : 0,
          tr = c.tTotal ? ((c.tTotal - c.tCorrect) / c.tTotal) : 0;
      if (rg > 0 || tr > 0) prof = { type: tr > rg ? "tritan" : "red-green",
                                     severity: Math.max(rg, tr) };
    }
    if (!prof) return;
    try {
      chrome.storage.local.get([PKEY], function (r) {
        var old = r && r[PKEY];
        // Only write when it actually changed, so a user who has since dragged the slider
        // is not overridden every time they revisit the site.
        if (old && old.type === prof.type && old.severity === prof.severity) return;
        var set = {};
        set[PKEY] = prof;
        if (!old) set[SKEY] = Math.round(prof.severity * 100);  // first measurement seeds it
        chrome.storage.local.set(set);
      });
    } catch (e) {}
  }
  try { syncProfile(); } catch (e) {}

  // Re-apply once the body exists (needed when injected at document_start).
  document.addEventListener("DOMContentLoaded", function () { if (current) engine.paint(current, strength); });

  // Third-party pages render content after load far more than our own does — infinite scroll,
  // route changes in a single-page app, lazily mounted panels. Without this, everything that
  // appears after the first paint stays uncorrected.
  if (window.MutationObserver && document.documentElement) {
    new MutationObserver(function (recs) {
      if (!current) return;
      for (var i = 0; i < recs.length; i++) if (recs[i].addedNodes.length) { repaintSoon(); return; }
    }).observe(document.documentElement, { childList: true, subtree: true });
  }

  // If the OS contrast setting changes while a mode is on, re-decide: the engine stands down
  // under forced-colors rather than fighting the operating system.
  if (window.matchMedia) {
    var mq = window.matchMedia("(forced-colors: active)");
    if (mq.addEventListener) mq.addEventListener("change", function () { if (current) engine.paint(current, strength); });
  }

  // Live updates: when the popup changes the saved mode, every open page reacts.
  try {
    chrome.storage.onChanged.addListener(function (changes, area) {
      if (area !== "local") return;
      if (changes[SKEY]) strength = changes[SKEY].newValue;
      if (changes[KEY]) apply(changes[KEY].newValue);
      else if (changes[SKEY] && current) engine.paint(current, strength);
    });
  } catch (e) {}
